# Generated by Django 5.2.4 on 2025-07-23 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='file_attached/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1, help_text='enter value between 1 and 5 :', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_tasks', to='task.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='task.tag'),
        ),
    ]
