# Generated by Django 5.2.4 on 2025-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_attached_file_alter_task_complete_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='related_tasks', to='task.task'),
        ),
    ]
