# Generated by Django 5.2.4 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
