# Generated by Django 5.2.4 on 2025-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file',
            field=models.FileField(blank=True, default=None, upload_to='file_attached/'),
        ),
    ]
