# Generated by Django 5.2.4 on 2025-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file_attached/'),
        ),
    ]
