# Generated by Django 5.2.4 on 2025-07-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_attached_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
