# Generated by Django 5.2.4 on 2025-07-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_rename_is_done_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
