# Generated by Django 5.2.4 on 2025-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OW', 'Owner'), ('MN', 'Manager'), ('CT', 'Contributor'), ('VW', 'Viewer')], default='VW', max_length=2),
        ),
    ]
