# Generated by Django 5.2.4 on 2025-07-22 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('access', models.CharField(choices=[('PB', 'Public'), ('PV', 'Private')], max_length=2)),
                ('category', models.CharField(choices=[('PR', 'Personal'), ('WR', 'Work'), ('TM', 'Team')], max_length=2)),
                ('is_archived', models.BooleanField(default=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('theme', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
